{{- if .Values.dependencies.minio.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    {{- include "my_project.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - name: api
      port: {{ .Values.dependencies.minio.service.apiPort }}
      targetPort: api
    - name: console
      port: {{ .Values.dependencies.minio.service.consolePort }}
      targetPort: console
  selector:
    {{- include "my_project.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "my_project.fullname" . }}-minio
  labels:
    {{- include "my_project.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      {{- include "my_project.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "my_project.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.dependencies.minio.image | quote }}
          imagePullPolicy: IfNotPresent
          args:
            - server
            - /data
            - --console-address
            - :9001
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appSecrets.name }}
                  key: MINIO_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appSecrets.name }}
                  key: MINIO_PASSWORD
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: api
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.dependencies.minio.storageSize }}
{{- end }}
